import {
  ALargeSmall,
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BookOpen,
  Bookmark,
  Bug,
  Castle,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUp,
  Clock,
  Crown,
  CopyCheck,
  Eye,
  File,
  FileText,
  Flag,
  Flame,
  Flower2,
  Folder,
  Gem,
  Gauge,
  Ghost,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  Heart,
  HelpCircle,
  Home,
  Landmark,
  KeyRound,
  Leaf,
  Link,
  Link2,
  List,
  ListFilter,
  Lock,
  Map,
  MapPin,
  Menu,
  Moon,
  Music,
  Package,
  Quote,
  Repeat,
  Repeat2,
  RotateCcw,
  Scroll,
  ScrollText,
  Search,
  Shield,
  Shuffle,
  SkipBack,
  SkipForward,
  Skull,
  Sparkles,
  Sword,
  Swords,
  Target,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TrendingUp,
  User,
  Users,
  Volume1,
  Volume2,
  VolumeX,
  Wrench,
  X,
  Zap,
  createIcons,
} from 'lucide';

const icons = {
  ALargeSmall, Activity, ArrowDown, ArrowLeft, ArrowRight, ArrowUp,
  BookOpen, Bookmark, Bug, Castle, CheckCircle, ChevronDown, ChevronLeft,
  ChevronRight, ChevronUp, ChevronsUp, Clock, CopyCheck, Crown, Eye, File, FileText, Flag, Flame,
  Flower2, Folder, Gauge, Gem, Ghost, Gift, GitBranch, GitMerge, Globe, Heart,
  HelpCircle, Home, KeyRound, Landmark, Leaf, Link, Link2, List, ListFilter, Lock, Map, MapPin,
  Menu, Moon, Music, Package, Quote, Repeat, Repeat2, RotateCcw, Scroll, ScrollText, Search,
  Shield, Shuffle, SkipBack, SkipForward, Skull, Sparkles, Sword, Swords, Target,
  ThumbsDown, ThumbsUp, Timer, TrendingUp, User, Users, Volume1, Volume2,
  VolumeX, Wrench, X, Zap,
};

export function refreshIcons() {
  createIcons({ icons });
}
